# Generated by Django 4.0.3 on 2022-03-15 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='end_timeslot',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_timeslot',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot_1',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot_2',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='upcoming', max_length=30),
        ),
        migrations.AlterModelTable(
            name='appointment',
            table='appointment',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.DeleteModel(
            name='Timeslot',
        ),
    ]
